---
title: "P8105_hw6_qy2234"
author: "Michael Yan"
date: "11/21/2019"
output: github_document
---

```{r setup, include=FALSE}
#### general setup
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(patchwork)
library(rvest)
library(modelr)
library(mgcv)
devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


# problem 1
```{r}
#### load and clean the data
birthweight_data = read_csv("./data/birthweight.csv") %>%
  mutate(babysex = as.factor(babysex),
         frace = as.factor(frace),
         malform = as.factor(malform),
         mrace = as.factor(mrace))

#### check for missing data in all columns
birthweight_data %>% 
  summarise_all(funs(sum(is.na(.)))) %>% 
  knitr::kable()
```
